name: Compile CircleMUD with Cygwin

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Cygwin
        run: |
          choco install cygwin
          choco install make
          choco install gcc

      - name: Compile CircleMUD
        run: |
          C:/cygwin64/bin/bash -lc "cd $GITHUB_WORKSPACE && make"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: CircleMUD-Windows
          path: ./circlemud-executable  # 替换为可执行文件路径
