
name: Compile CircleMUD for ARM64

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cross-compile tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu make

      - name: Configure CircleMUD for ARM64
        run: |
          ./configure CC=aarch64-linux-gnu-gcc

      - name: Compile CircleMUD for ARM64
        run: |
          cd src
          make all

      - name: List files in src directory
        run: ls -la src

      - name: Upload ARM64 binary
        uses: actions/upload-artifact@v3
        with:
          name: CircleMUD-ARM64
          path: ./src/circle  # 替换为实际生成的可执行文件路径
