

name: Compile CircleMUD for ARM64

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cross-compile tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu make

      - name: Compile CircleMUD for ARM64
        run: |
          make clean || true  # 确保没有之前的编译产物
          CC=aarch64-linux-gnu-gcc make

      - name: Upload ARM64 binary
        uses: actions/upload-artifact@v3
        with:
          name: CircleMUD-ARM64
          path: ./circlemud-executable  # 替换为生成的 ARM64 可执行文件的路径
          
